using UnityEngine;
using UnityEngine.UI;
using System;
using DG.Tweening;
using Sirenix.OdinInspector;

// This file was auto generated by CodeLinker
// update time : 2021/11/18 12:15:16
public partial class DashboardPage : Page
{
	private VerticalLayoutGroup _itemRoot;
	protected VerticalLayoutGroup ItemRoot
	{
		get
		{
			if(_itemRoot == null)
			{
				var t = CodeLinkerUtil.FindByPath(transform, "$itemRoot");
				_itemRoot = t.gameObject.GetComponent<VerticalLayoutGroup>();
			}
			return _itemRoot;
		}
	}

	private DashboardItemView _prefab_dashboardItemView;
	protected DashboardItemView Prefab_dashboardItemView
	{
		get
		{
			if(_prefab_dashboardItemView == null)
			{
				var t = CodeLinkerUtil.FindByPath(transform, "$prefab_dashboardItemView");
				_prefab_dashboardItemView = t.gameObject.GetComponent<DashboardItemView>();
			}
			return _prefab_dashboardItemView;
		}
	}

}
