using UnityEngine.UI;

// This file was auto generated by CodeLinker
// update time : 2023/05/04 17:47:39
public partial class HotPresetPage : Page
{
	private VerticalLayoutGroup _itemRoot;
	protected VerticalLayoutGroup ItemRoot
	{
		get
		{
			if(_itemRoot == null)
			{
				var t = CodeLinkerUtil.FindByPath(transform, "Pannel/$itemRoot");
				_itemRoot = t.gameObject.GetComponent<VerticalLayoutGroup>();
			}
			return _itemRoot;
		}
	}

	private DashboardItemView _prefab_dashboardItemView;
	protected DashboardItemView Prefab_dashboardItemView
	{
		get
		{
			if(_prefab_dashboardItemView == null)
			{
				var t = CodeLinkerUtil.FindByPath(transform, "Pannel/$prefab_dashboardItemView");
				_prefab_dashboardItemView = t.gameObject.GetComponent<DashboardItemView>();
			}
			return _prefab_dashboardItemView;
		}
	}

}
