using UnityEngine;
using UnityEngine.UI;

// This file was auto generated by CodeLinker
// update time : 2022/09/20 14:38:38
public partial class LauncherUiManager : SceneObject<LauncherUiManager>
{
	private CanvasRenderer _normalLayer;
	protected CanvasRenderer NormalLayer
	{
		get
		{
			if(_normalLayer == null)
			{
				var t = CodeLinkerUtil.FindByPath(transform, "$NormalLayer");
				_normalLayer = t.gameObject.GetComponent<CanvasRenderer>();
			}
			return _normalLayer;
		}
	}

	private CanvasRenderer _topLayer;
	protected CanvasRenderer TopLayer
	{
		get
		{
			if(_topLayer == null)
			{
				var t = CodeLinkerUtil.FindByPath(transform, "$TopLayer");
				_topLayer = t.gameObject.GetComponent<CanvasRenderer>();
			}
			return _topLayer;
		}
	}

	private Image _debugerButton;
	protected Image DebugerButton
	{
		get
		{
			if(_debugerButton == null)
			{
				var t = CodeLinkerUtil.FindByPath(transform, "$TopLayer/$DebugerButton");
				_debugerButton = t.gameObject.GetComponent<Image>();
			}
			return _debugerButton;
		}
	}

}
