using UnityEngine;
using UnityEngine.UI;

// This file was auto generated by CodeLinker
// update time : 2023/04/20 11:57:08
public partial class LauncherDialog : MonoBehaviour
{
	private Text _text_content;
	protected Text Text_content
	{
		get
		{
			if(_text_content == null)
			{
				var t = CodeLinkerUtil.FindByPath(transform, "root/$text_content");
				_text_content = t.gameObject.GetComponent<Text>();
			}
			return _text_content;
		}
	}

	private Text _text_title;
	protected Text Text_title
	{
		get
		{
			if(_text_title == null)
			{
				var t = CodeLinkerUtil.FindByPath(transform, "root/$text_title");
				_text_title = t.gameObject.GetComponent<Text>();
			}
			return _text_title;
		}
	}

	private Text _text_tip;
	protected Text Text_tip
	{
		get
		{
			if(_text_tip == null)
			{
				var t = CodeLinkerUtil.FindByPath(transform, "root/$text_tip");
				_text_tip = t.gameObject.GetComponent<Text>();
			}
			return _text_tip;
		}
	}

	private CanvasRenderer _group_ConfirmCancel;
	protected CanvasRenderer Group_ConfirmCancel
	{
		get
		{
			if(_group_ConfirmCancel == null)
			{
				var t = CodeLinkerUtil.FindByPath(transform, "node1/$group_ConfirmCancel");
				_group_ConfirmCancel = t.gameObject.GetComponent<CanvasRenderer>();
			}
			return _group_ConfirmCancel;
		}
	}

	private Text _cancelText;
	protected Text CancelText
	{
		get
		{
			if(_cancelText == null)
			{
				var t = CodeLinkerUtil.FindByPath(transform, "node1/$group_ConfirmCancel/CancelButton/$CancelText");
				_cancelText = t.gameObject.GetComponent<Text>();
			}
			return _cancelText;
		}
	}

	private Text _confirmText;
	protected Text ConfirmText
	{
		get
		{
			if(_confirmText == null)
			{
				var t = CodeLinkerUtil.FindByPath(transform, "node1/$group_ConfirmCancel/ConfirmButton/$ConfirmText");
				_confirmText = t.gameObject.GetComponent<Text>();
			}
			return _confirmText;
		}
	}

	private CanvasRenderer _group_ConfirmOnly;
	protected CanvasRenderer Group_ConfirmOnly
	{
		get
		{
			if(_group_ConfirmOnly == null)
			{
				var t = CodeLinkerUtil.FindByPath(transform, "node2/$group_ConfirmOnly");
				_group_ConfirmOnly = t.gameObject.GetComponent<CanvasRenderer>();
			}
			return _group_ConfirmOnly;
		}
	}

	private Text _confirmOnlyText;
	protected Text ConfirmOnlyText
	{
		get
		{
			if(_confirmOnlyText == null)
			{
				var t = CodeLinkerUtil.FindByPath(transform, "node2/$group_ConfirmOnly/ConfirmButton/$ConfirmOnlyText");
				_confirmOnlyText = t.gameObject.GetComponent<Text>();
			}
			return _confirmOnlyText;
		}
	}

}
