using UnityEngine;
using UnityEngine.UI;

// This file was auto generated by CodeLinker
// update time : 2023/03/10 23:57:14
public partial class LauncherInputDialog : MonoBehaviour
{
	private Text _text_content;
	protected Text Text_content
	{
		get
		{
			if(_text_content == null)
			{
				var t = CodeLinkerUtil.FindByPath(transform, "root/$text_content");
				_text_content = t.gameObject.GetComponent<Text>();
			}
			return _text_content;
		}
	}

	private InputField _input;
	protected InputField Input
	{
		get
		{
			if(_input == null)
			{
				var t = CodeLinkerUtil.FindByPath(transform, "root/$input");
				_input = t.gameObject.GetComponent<InputField>();
			}
			return _input;
		}
	}

	private CanvasRenderer _group_ConfirmCancel;
	protected CanvasRenderer Group_ConfirmCancel
	{
		get
		{
			if(_group_ConfirmCancel == null)
			{
				var t = CodeLinkerUtil.FindByPath(transform, "node1/$group_ConfirmCancel");
				_group_ConfirmCancel = t.gameObject.GetComponent<CanvasRenderer>();
			}
			return _group_ConfirmCancel;
		}
	}

	private Text _cancelText;
	protected Text CancelText
	{
		get
		{
			if(_cancelText == null)
			{
				var t = CodeLinkerUtil.FindByPath(transform, "node1/$group_ConfirmCancel/CancelButton/$CancelText");
				_cancelText = t.gameObject.GetComponent<Text>();
			}
			return _cancelText;
		}
	}

	private Text _confirmText;
	protected Text ConfirmText
	{
		get
		{
			if(_confirmText == null)
			{
				var t = CodeLinkerUtil.FindByPath(transform, "node1/$group_ConfirmCancel/ConfirmButton/$ConfirmText");
				_confirmText = t.gameObject.GetComponent<Text>();
			}
			return _confirmText;
		}
	}

}
