using UnityEngine;
using UnityEngine.UI;

// This file was auto generated by CodeLinker
// update time : 2022/08/22 11:35:30
public partial class LauncherWeihuPage : MonoBehaviour
{
	private Image _button_frefreshFrezen;
	protected Image Button_frefreshFrezen
	{
		get
		{
			if(_button_frefreshFrezen == null)
			{
				var t = CodeLinkerUtil.FindByPath(transform, "Pannel/$button_frefreshFrezen");
				_button_frefreshFrezen = t.gameObject.GetComponent<Image>();
			}
			return _button_frefreshFrezen;
		}
	}

	private Image _button_refresh;
	protected Image Button_refresh
	{
		get
		{
			if(_button_refresh == null)
			{
				var t = CodeLinkerUtil.FindByPath(transform, "Pannel/$button_refresh");
				_button_refresh = t.gameObject.GetComponent<Image>();
			}
			return _button_refresh;
		}
	}

	private Text _text_content;
	protected Text Text_content
	{
		get
		{
			if(_text_content == null)
			{
				var t = CodeLinkerUtil.FindByPath(transform, "Pannel/Scroll View/Viewport/$text_content");
				_text_content = t.gameObject.GetComponent<Text>();
			}
			return _text_content;
		}
	}

}
