using UnityEngine;
using UnityEngine.UI;

// This file was auto generated by CodeLinker
// update time : 2023/04/20 12:06:03
public partial class LauncherGameResultPop : MonoBehaviour
{
	private Text _txt_judgement;
	protected Text Txt_judgement
	{
		get
		{
			if(_txt_judgement == null)
			{
				var t = CodeLinkerUtil.FindByPath(transform, "root/Node_Informations/Node_evaluation/Node_evaluate1/$Txt_judgement");
				_txt_judgement = t.gameObject.GetComponent<Text>();
			}
			return _txt_judgement;
		}
	}

	private Text _txt_costTime;
	protected Text Txt_costTime
	{
		get
		{
			if(_txt_costTime == null)
			{
				var t = CodeLinkerUtil.FindByPath(transform, "root/Node_Informations/Node_evaluation/Node_evaluate2/$Txt_costTime");
				_txt_costTime = t.gameObject.GetComponent<Text>();
			}
			return _txt_costTime;
		}
	}

	private Image _node_prize;
	protected Image Node_prize
	{
		get
		{
			if(_node_prize == null)
			{
				var t = CodeLinkerUtil.FindByPath(transform, "root/Node_Informations/$Node_prize");
				_node_prize = t.gameObject.GetComponent<Image>();
			}
			return _node_prize;
		}
	}

	private GridLayoutGroup _list_items;
	protected GridLayoutGroup List_items
	{
		get
		{
			if(_list_items == null)
			{
				var t = CodeLinkerUtil.FindByPath(transform, "root/Node_Informations/$Node_prize/Node_items/Viewport/$List_items");
				_list_items = t.gameObject.GetComponent<GridLayoutGroup>();
			}
			return _list_items;
		}
	}

	private LauncherMutexComponent _switcher_reward;
	protected LauncherMutexComponent Switcher_reward
	{
		get
		{
			if(_switcher_reward == null)
			{
				var t = CodeLinkerUtil.FindByPath(transform, "root/Node_Informations/$Node_prize/$Switcher_reward");
				_switcher_reward = t.gameObject.GetComponent<LauncherMutexComponent>();
			}
			return _switcher_reward;
		}
	}

	private HorizontalLayoutGroup _list_rewards;
	protected HorizontalLayoutGroup List_rewards
	{
		get
		{
			if(_list_rewards == null)
			{
				var t = CodeLinkerUtil.FindByPath(transform, "root/Node_Informations/$Node_prize/$List_rewards");
				_list_rewards = t.gameObject.GetComponent<HorizontalLayoutGroup>();
			}
			return _list_rewards;
		}
	}

}
