using DG.Tweening;
using UnityEngine;

// This file was auto generated by CodeLinker
// update time : 2023/01/11 12:41:00
public partial class BlockFloating : Floating
{
	private GameObject _normalStyle;
	protected GameObject NormalStyle
	{
		get
		{
			if(_normalStyle == null)
			{
				var t = CodeLinkerUtil.FindByPath(transform, "$normalStyle");
				_normalStyle = t.gameObject;
			}
			return GameObject;
		}
	}

	private GameObject _loginPageStyle;
	protected GameObject LoginPageStyle
	{
		get
		{
			if(_loginPageStyle == null)
			{
				var t = CodeLinkerUtil.FindByPath(transform, "$loginPageStyle");
				_loginPageStyle = t.gameObject;
			}
			return _loginPageStyle;
		}
	}

}
