using System.Collections;
using UnityEngine;
using UnityEngine.EventSystems;
using UnityEngine.UI;

/// <summary>
/// Generated by GPT-4
/// </summary>
public class LimitedClicker : MonoBehaviour, IPointerClickHandler
{
    [SerializeField]
    private float clickInterval = 0.2f; // 点击间隔时间（秒）
    [SerializeField]
    private MonoBehaviour button;

    private float lastClickTime = -1f;
    private bool isEnabled = true;

    void Start()
    {
        button = GetComponent<Button>();
    }

    public void OnPointerClick(PointerEventData eventData)
    {
        if (!isEnabled) return;

        float currentTime = Time.time;

        // 如果上次点击距离当前时间大于等于设定的间隔时间，则执行操作
        if (currentTime - lastClickTime >= clickInterval || lastClickTime < 0)
        {
            lastClickTime = currentTime;

            // 禁用按钮，并在指定时间后启用
            if (button != null)
            {
                button.enabled = false;
                StartCoroutine(EnableButtonAfterDelay(clickInterval));
            }
        }
    }

    IEnumerator EnableButtonAfterDelay(float delay)
    {
        yield return new WaitForSeconds(delay);
        button.enabled = true;
    }

    // 控制是否响应点击事件
    public void SetEnabled(bool enabled)
    {
        isEnabled = enabled;
        if (button != null)
        {
            button.enabled = enabled;
        }
    }
}