using UnityEngine.UI;

// This file was auto generated by CodeLinker
// update time : 2023/03/29 20:35:45
public partial class LoadingFloating : Floating
{
	private Image _bg;
	protected Image Bg
	{
		get
		{
			if(_bg == null)
			{
				var t = CodeLinkerUtil.FindByPath(transform, "whiteBg/$bg");
				_bg = t.gameObject.GetComponent<Image>();
			}
			return _bg;
		}
	}

	private Text _tip_loading;
	protected Text Tip_loading
	{
		get
		{
			if(_tip_loading == null)
			{
				var t = CodeLinkerUtil.FindByPath(transform, "offset/$tip_loading");
				_tip_loading = t.gameObject.GetComponent<Text>();
			}
			return _tip_loading;
		}
	}

	private Text _progress_text;
	protected Text Progress_text
	{
		get
		{
			if(_progress_text == null)
			{
				var t = CodeLinkerUtil.FindByPath(transform, "offset/Layout/$progress_text");
				_progress_text = t.gameObject.GetComponent<Text>();
			}
			return _progress_text;
		}
	}

	private SmoothProgressBar _progress;
	protected SmoothProgressBar Progress
	{
		get
		{
			if(_progress == null)
			{
				var t = CodeLinkerUtil.FindByPath(transform, "offset/$Progress");
				_progress = t.gameObject.GetComponent<SmoothProgressBar>();
			}
			return _progress;
		}
	}

}
